---
  - name: GIT - check if GIT was installed from the source before
    stat:
      path: /home/vagrant/tmp/git-{{git_install_from_source_version}}
    register: git_install_from_source_folder

  - block:
    - name: GIT - install iuscommunity repository package
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: present

    - name: GIT - install GIT
      yum:
        name: git2u
        state: present

    when: git_install_from_source != "1" and git_install_from_source_folder.stat.exists == false

  - file:
      path: /home/vagrant/tmp
      state: directory
      mode: 0755
    when: git_install_from_source == "1"

  - name: GIT - download and unarchive a GIT {{git_install_from_source_version}} tarball
    unarchive:
      src: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{git_install_from_source_version}}.tar.gz
      dest: /home/vagrant/tmp
      remote_src: yes
      creates: /home/vagrant/tmp/git-{{git_install_from_source_version}}
    register: git_unarchive_result
    when: git_install_from_source == "1"

  - block:
    - name: GIT - install dependencies
      yum:
        name:
          - dh-autoreconf
          - curl-devel
          - expat-devel
          - gettext-devel
          - openssl-devel
          - perl-devel
          - zlib-devel
          - asciidoc
          - xmlto
          - docbook2X
        state: present

    - name: GIT - create symlink /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
      file:
        src: /usr/bin/db2x_docbook2texi
        dest: /usr/bin/docbook2x-texi
        state: link

    - name: GIT - upload GIT {{git_install_from_source_version}} install script /home/vagrant/git-install.sh
      template:
        src: home/vagrant/git-install.sh.j2
        dest: /home/vagrant/git-install.sh
        owner: vagrant
        group: vagrant
        mode: 0744

    - name: GIT - make GIT {{git_install_from_source_version}}
      command: sh /home/vagrant/git-install.sh
      register: git_result

    when: git_install_from_source == "1" and git_unarchive_result.changed